encoding: utf-8
#port: 5678
#host: 0.0.0.0

title: 梦里依稀的小湖
keywords: [dreaminlake, 花生米, 梦里依稀的小湖]
description: '有些事，记下来是不错的选择...'

exclude: [webpack.config.js, package.json, Gemfile, Gemfile.lock, src, node_modules]
gems: [jekyll-paginate, jemoji]

permalink: /:title.html
highlighter: rouge
markdown: kramdown
kramdown: 
  auto_ids:       true
  auto_id_prefix: 'id-'
  toc_levels:     '2,3'
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
emoji:
    src: 'https://api.fooleap.org'
paginate: 10
repository: dreaminlake/dreaminlake.github.io

nickname: dreaminlake
home: https://dreaminlake.com
api: https://api.dreaminlake.com
IMG_PATH: https://source.dreaminlake.com
tongji: ' '
analytics: 'UA-78691951-1'

theme: jekyll-theme-hacker